version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    security_opt:
      - seccomp:unconfined
    depends_on:
      - db
  db:
    image: mysql:5.7.19
    environment:
       - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
